module.exports = {
    USER_JOINED: 'USER_JOINED',
    ADMIN_JOINED: 'ADMIN_JOINED',
    USER_STATE_CHANGED: 'USER_STATE_CHANGED',
    MAXADMIN_JOINED: 'MAXADMIN_JOINED',
    SEND_USER_LIST: 'SEND_USER_LIST',
    MIDIIN: 'MIDIIN'
}